using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    internal class Program
    {
        static void Main(string[] args)
        {
            int number1 = 1;
            int number2 = 4;
            Console.WriteLine(number1 + number2);
            Console.WriteLine(number1 - number2);
            Console.WriteLine(number1 * number2);
            Console.WriteLine(number1 / number2);
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");


            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
            Console.WriteLine("Hello World From C# App");
        }
    }
}
